/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3 */

#ifndef PB_SENSOCARE_MESSAGES_INTERFACE_PB_H_INCLUDED
#define PB_SENSOCARE_MESSAGES_INTERFACE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _sensocare_messages_Measure {
    uint64_t timestamp;
    float value;
} sensocare_messages_Measure;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define sensocare_messages_Measure_init_default  {0, 0}
#define sensocare_messages_Measure_init_zero     {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define sensocare_messages_Measure_timestamp_tag 1
#define sensocare_messages_Measure_value_tag     2

/* Struct field encoding specification for nanopb */
#define sensocare_messages_Measure_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, FLOAT,    value,             2)
#define sensocare_messages_Measure_CALLBACK NULL
#define sensocare_messages_Measure_DEFAULT NULL

extern const pb_msgdesc_t sensocare_messages_Measure_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sensocare_messages_Measure_fields &sensocare_messages_Measure_msg

/* Maximum encoded size of messages (where known) */
#define sensocare_messages_Measure_size          40

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
